version: "3"

networks:
  code:
    driver: bridge

services:
  php_fpm:
      build: 
        dockerfile: Dockerfile
        context: ./php/
      container_name: my-php_fpm
      working_dir: /usr/share/nginx/code
      networks:
        - code
      volumes:
        - ./nginx/code:/usr/share/nginx/code
  nginx:
      build: 
        dockerfile: Dockerfile
        context: ./nginx/
      container_name: my-nginx
      working_dir: /usr/share/nginx/code
      networks:
        - code
      ports:
          - "8080:80"
  my-mysql:
    image: mysql:latest
    container_name: my-mysql
    networks:
      - code
    volumes:
      - ./sql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
